BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DEMOTABLE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE DEMOTABLE (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(20)
);
